# Generated by Django 5.0.3 on 2024-03-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата и время измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temp',
            field=models.TextField(verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
