# Generated by Django 5.0.3 on 2024-03-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='temp',
            new_name='temperature',
        ),
    ]
