# Generated by Django 5.0.3 on 2024-03-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_rename_date_measurement_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor', verbose_name='Название датчика'),
        ),
    ]
